// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCluster(arg1) {
  return window['go']['main']['App']['AddCluster'](arg1);
}

export function DeleteCluster(arg1) {
  return window['go']['main']['App']['DeleteCluster'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function ImportFromEnvironment() {
  return window['go']['main']['App']['ImportFromEnvironment']();
}

export function PreviewTargets(arg1) {
  return window['go']['main']['App']['PreviewTargets'](arg1);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RunOperation(arg1) {
  return window['go']['main']['App']['RunOperation'](arg1);
}

export function SaveBatchSettings(arg1) {
  return window['go']['main']['App']['SaveBatchSettings'](arg1);
}

export function SaveDBFunctions(arg1) {
  return window['go']['main']['App']['SaveDBFunctions'](arg1);
}

export function SaveUISettings(arg1) {
  return window['go']['main']['App']['SaveUISettings'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateCluster(arg1, arg2) {
  return window['go']['main']['App']['UpdateCluster'](arg1, arg2);
}
