// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddCategory(arg1:model.CategoryInput):Promise<model.Category>;

export function AddCluster(arg1:model.ClusterInput):Promise<model.Cluster>;

export function CheckForUpdate():Promise<model.UpdateInfo>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteCluster(arg1:string):Promise<void>;

export function GetAppVersion():Promise<model.AppVersion>;

export function GetConfig():Promise<model.Config>;

export function GetConfigPath():Promise<string>;

export function GetDefaultTemplates():Promise<model.DefaultTemplates>;

export function GetPendingUpdate():Promise<model.UpdateInfo>;

export function LoadRoleDependencies(arg1:model.RoleDependenciesRequest):Promise<Array<model.ClusterRoleDependencies>>;

export function LoadRoleDetails(arg1:model.RoleDetailsRequest):Promise<Array<model.ClusterRoleDetail>>;

export function PreviewTargets(arg1:model.RunRequest):Promise<Array<model.Cluster>>;

export function ReloadConfig():Promise<model.Config>;

export function RunOperation(arg1:model.RunRequest):Promise<Array<model.ClusterResult>>;

export function RunRoleBatch(arg1:model.RoleBatchRequest):Promise<Array<model.ClusterResult>>;

export function SaveBatchSettings(arg1:model.BatchSettings):Promise<void>;

export function SaveClusters(arg1:model.ClustersConfig):Promise<void>;

export function SaveCommentFields(arg1:Array<model.CommentField>):Promise<void>;

export function SaveDBFunctions(arg1:model.DBFunctions):Promise<void>;

export function SaveDBReads(arg1:model.DBReads):Promise<void>;

export function SaveParentRoles(arg1:Array<string>):Promise<void>;

export function SaveSearchColumns(arg1:Array<model.SearchColumn>):Promise<void>;

export function SaveSettings(arg1:model.SettingsPayload):Promise<void>;

export function SaveTargetSelection(arg1:model.TargetSelection):Promise<void>;

export function SaveUISettings(arg1:model.UISettings):Promise<void>;

export function SaveWindowSize(arg1:number,arg2:number):Promise<void>;

export function SearchRoles(arg1:model.RoleSearchRequest):Promise<Array<model.ClusterRoleMatches>>;

export function SetUpdateSeenVersion(arg1:string):Promise<void>;

export function TestConnection(arg1:model.TestConnectionRequest):Promise<void>;

export function TestConnectionInput(arg1:model.ClusterInput,arg2:model.AuthContext):Promise<void>;

export function UpdateCategory(arg1:string,arg2:model.CategoryInput):Promise<model.Category>;

export function UpdateCluster(arg1:string,arg2:model.ClusterInput):Promise<model.Cluster>;
