// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddCluster(arg1:model.ClusterInput):Promise<model.Cluster>;

export function DeleteCluster(arg1:string):Promise<void>;

export function GetAppVersion():Promise<model.AppVersion>;

export function GetConfig():Promise<model.Config>;

export function GetConfigPath():Promise<string>;

export function ImportFromEnvironment():Promise<model.EnvImport>;

export function PreviewTargets(arg1:model.RunRequest):Promise<Array<model.Cluster>>;

export function ReloadConfig():Promise<model.Config>;

export function RunOperation(arg1:model.RunRequest):Promise<Array<model.ClusterResult>>;

export function SaveBatchSettings(arg1:model.BatchSettings):Promise<void>;

export function SaveDBFunctions(arg1:model.DBFunctions):Promise<void>;

export function SaveUISettings(arg1:model.UISettings):Promise<void>;

export function TestConnection(arg1:model.TestConnectionRequest):Promise<void>;

export function UpdateCluster(arg1:string,arg2:model.ClusterInput):Promise<model.Cluster>;
